apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-init-{{ randAlphaNum 5 | lower }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tdengine.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  containers:
    - name: "{{ .Release.Name }}-init"
      image: "{{ .Values.Image }}:{{ .Values.ImageTag }}"
      command: ["bash", "+x", "/root/cluster_init.sh","{{ template "tdengine.fullname" . }}-1.{{ template "tdengine.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:6030","{{ template "tdengine.fullname" . }}-2.{{ template "tdengine.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:6030"]
      env:
        - name: STATEFULSET_NAME
          value: "{{ template "tdengine.fullname" . }}"
        - name: STATEFULSET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TAOS_serverPort
          value: "6030"
        - name: TAOS_firstEp
          value: "$(STATEFULSET_NAME)-0.$(STATEFULSET_NAME).$(STATEFULSET_NAMESPACE).svc.cluster.local:$(TAOS_serverPort)"
        - name: TAOS_secondEp
          value: "$(STATEFULSET_NAME)-1.$(STATEFULSET_NAME).$(STATEFULSET_NAMESPACE).svc.cluster.local:$(TAOS_serverPort)"
  restartPolicy: Never
